name: Python linters and code checking

on: 
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  check_code:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylama black
        # Add your dependences here if your package can not compile without them.
    - name: Patch pylama
      run: |
        # Current pylama version fails if you try to check empty files. This patch fix the crash.
        patch $(echo $(pip show pylama | grep "Location" | sed "s/Location: //g")"/pylama/context.py") pylama.patch
    - name: Autoformat code with black
      run: python -m black -l 100 $(git ls-files '*.py')
    - name: Check code with pylama
      run: python -m pylama $(git ls-files '*.py')
